
version: "3"
services:
    run:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      ports: 
        - "5000:5000"
        - "5001:5001"
      command: dotnet run --project BlazeSnes
    watch-run:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      ports: 
        - "5000:5000"
        - "5001:5001"
      command: dotnet watch --project BlazeSnes run
    publish:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: dotnet publish -c Release
    test:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: dotnet test --logger:"console;verbosity=detailed" --collect:"XPlat Code Coverage"
    format:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: dotnet format
    coverage:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: bash -c "chmod +x ./test-coverage.sh && ./test-coverage.sh"