
version: "3"
services:
    run:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      ports: 
        - "5000:5000"
        - "5001:5001"
      command: dotnet run
    publish:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: dotnet publish -c Release
    test:
      build:
        context: .
        dockerfile: ./.devcontainer/Dockerfile
      volumes:
        - ./:/work
      working_dir: /work
      command: dotnet test