name: Deploy Netlify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker-compose run publish
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npx netlify-cli deploy --prod --dir=./BlazeSnes/bin/Release/netstandard2.1/publish/wwwroot/
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    - uses: actions/upload-artifact@v2
      with:
        name: blaze-snes-wwwroot.zip
        path: BlazeSnes/bin/Release/netstandard2.1/publish/wwwroot/